name: Set release version
on: 
  release:
    types: [published]
jobs:
  set-release-version:
    name: Set release version
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps: 
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Setup Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '20.8.1'
      - name: Install independecies
        run: npm install
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release